site_name: YinChao's Wiki

theme:
    name: 'material'
    include_sidebar: true
    
nav:
    - Home: index.md
    - env_build: [env_build/my_wiki.md]
    - python: 
        - environment: [
                  python/python_setup.md,
                  python/python_package.md,
                  python/useful_package.md,
                  python/PEP8_standard.md,
                  python/requirements.md,
                  python/jupyter.md,
                  python/multi_version.md
        ]
        - basic: [ 
                  python/dict.md,
                  python/file.md,
                  python/dataframe.md,
                  python/type.md,
                  python/list.md,
                  python/shell.md,
                  python/network.md,
                  python/path.md,
                  python/copy.md
        ]
        - usefule_module: [
        ]
               
    - linux: linux/top.md
    
    - git: 
        - environment: [
                  git/local_git.md, 
                  git/aliyun_git.md
        ]
        - basic: [
                  git/common_cmd.md,
                  git/git_reset.md,
                  git/add.md,
                  git/clear.md,
                  git/branch.md,
                  git/branch_recovery.md
        ]
