site_name: YinChao's Wiki
site_description: 个人知识体系
site_author: YinChao

theme:
    name: 'material'
    include_sidebar: true

extra:
  search:
    language: 'jp'
    
nav:
    - index: index.md
    - 作者简介: 作者简介.md
    - 技术栈简介: 技术栈简介.md
    - basic: [
                  basic/YAML详解.md,
    ]
    - 环境搭建: [
                  env_build/my_wiki.md,
                  env_build/tomcat.md,
                  env_build/rabbitmq_server.md,
                  env_build/google_ssr.md,
                  env_build/阿里云搭建git私有仓库.md,
        ]
    - python: 
        - environment: [
                  python/environment/python_setup.md,
                  python/environment/python_package.md,
                  python/environment/useful_package.md,
                  python/environment/PEP8_standard.md,
                  python/environment/requirements.md,
                  python/environment/jupyter.md,
                  python/environment/multi_version.md,
                  python/environment/pip.md,
        ]
        - basic: [ 
                  python/basic/date_time.md,
                  python/basic/package_module.md,
                  python/basic/dict.md,
                  python/basic/file.md,
                  python/basic/json.md,
                  python/basic/Series.md,
                  python/basic/dataframe.md,
                  python/basic/type.md,
                  python/basic/map.md,
                  python/basic/Lambda.md,
                  python/basic/list.md,
                  python/basic/shell.md,
                  python/basic/network.md,
                  python/basic/path.md,
                  python/basic/regular_expression.md,
                  python/basic/迭代器和生成器.md,
                  python/basic/copy.md
        ]
        - useful_module: [
                  python/useful_module/SerialPort.md,
                  python/useful_module/threading_quit.md,
                  python/useful_module/app_frozen.md,
                  python/useful_module/RMQ.md,
                  python/useful_module/进程操作.md,
                  python/useful_module/excel操作.md,
                  python/useful_module/tkinter.md,
                  python/useful_module/auto_inform.md,
                  python/useful_module/crawler_example.md,
                  python/useful_module/sort.md,
                  python/useful_module/数据可视化.md,
                  python/useful_module/uart.md,
                  python/useful_module/usb_device.md,
                  python/useful_module/logging实用宝典.md,
                  python/useful_module/logging模块YAML配置说明.md,
                  python/useful_module/dos2linux.md,
                  python/useful_module/聊天机器人.md,
                  python/useful_module/买房还是租房.md,
                  
        ]
        - tools: [
                  python/tools/pyinstaller.md,
                  python/tools/supervisor详解.md,
        ]
               
    - C/C++:  
        - basic: [ 
                  c/shift.md,
                  c/inline.md,
                  c/hash.md,
                  c/file.md,
                  c/memory.md,
                  c/strings.md,
                  c/vs2013_err_code.md,
        ]
        - useful_module: [
                  c/fifo.md,
                  c/search_directory.md,
                  c/CSLink单链表.md,
                  c/json.md,
                  c/KMP.md,
                  c/csv_io.md,
                  c/pcre正则表达式.md,
                  c/merge_sort.md,
                  c/AT指令集.md,
                  c/serial_port.md,
                  c/makefile.md,
        ]
               
    - linux:  [   
                  linux/sleep.md,
                  linux/top.md,
                  linux/VM文件共享.md,
                  linux/vim.md,
                  linux/压缩解压.md,
                  linux/搜狗输入法安装.md,
                  linux/自动登录.md,
                  linux/ssh登陆与文件拷贝.md,
                  linux/Linux和Windows共享文件.md,
                  linux/复位usb设备.md,
                  linux/Raspberry Pi网络问题.md,
        ]
    
    - git: 
        - environment: [
                  git/local_git.md, 
                  git/aliyun_git.md
        ]
        - basic: [
                  git/common_cmd.md,
                  git/git_reset.md,
                  git/add.md,
                  git/clear.md,
                  git/branch.md,
                  git/branch_recovery.md
        ]
        
    - 优化技术: [
                  opt/优化技术综述.md,
                  opt/exp近似运算.md,
                  opt/log快速计算.md,
                  opt/profile工具.md,
                  opt/除法运算.md,
                  opt/复数求模近似运算.md,
                  opt/快速取余.md,
                  opt/提高cache命中率.md,
    
        ]
        
    - 高效率工作: 
        - 方法: [
                  tools/OKR工作法.md,
                  tools/GTD工作法.md,
                  
                  tools/Scrum敏捷框架.md,
        ]
        - 工具: [
                  tools/超高效率工具.md,
                  tools/icon.md,
                  tools/mkdocs.md,
                  tools/notepad2.md,
        ]

    - 随笔文章: 
        - 段子: [
                  article/joke/程序员漫画.md,
                  article/joke/996与007.md,
        ]
        
        - 经验: [
                  article/搞了10年技术后学到的7个真理.md,
        ]
        
        - 牛逼的人: [
                  article/圈内大佬/雷军.md,
        ]
        - 随笔: [
        ]
        - 新闻: [
                  article/报纸摘要/breaking_news.md,
                  article/报纸摘要/精选报纸摘要.md,
        ]
        
   