site_name: YinChao's Wiki

theme:
    name: 'material'
    include_sidebar: true
    
nav:
    - Home: index.md
    - env_build: [env_build/my_wiki.md, env_build/aliyun_git.md]
    - python: python/dict.md
