site_name: YinChao's Wiki
site_description: 个人知识体系
site_author: YinChao

theme:
    name: 'material'
    include_sidebar: true

extra:
  search:
    language: 'jp'
    
nav:
    - index: index.md
    - about: about.md
    - env_build: [env_build/my_wiki.md]
    - python: 
        - environment: [
                  python/python_setup.md,
                  python/python_package.md,
                  python/useful_package.md,
                  python/PEP8_standard.md,
                  python/requirements.md,
                  python/jupyter.md,
                  python/multi_version.md
        ]
        - basic: [ 
                  python/dict.md,
                  python/file.md,
                  python/dataframe.md,
                  python/type.md,
                  python/list.md,
                  python/shell.md,
                  python/network.md,
                  python/path.md,
                  python/regular_expression.md,
                  python/copy.md
        ]
        - useful_module: [
                  python/crawler_example.md,
                  python/sort_by_num.md,
        ]
        - tools: [
                  python/pyinstaller.md,
        ]
               
    - linux: linux/top.md
    
    - git: 
        - environment: [
                  git/local_git.md, 
                  git/aliyun_git.md
        ]
        - basic: [
                  git/common_cmd.md,
                  git/git_reset.md,
                  git/add.md,
                  git/clear.md,
                  git/branch.md,
                  git/branch_recovery.md
        ]
        
    - 优化技术: [
                  opt/优化技术综述.md,
                  opt/exp近似运算.md,
                  opt/log快速计算.md,
                  opt/profile工具.md,
                  opt/除法运算.md,
                  opt/复数求模近似运算.md,
                  opt/快速取余.md,
                  opt/提高cache命中率.md,
    
        ]
        
    - 常用工具: 
        - tools: [
                  tools/icon.md,
                  tools/mkdocs.md,
        ]

    - 随笔文章: []