site_name: YinChao's Wiki
site_description: 个人知识体系
site_author: YinChao

theme:
    name: 'material'
    include_sidebar: true

extra:
  search:
    language: 'jp'
    
nav:
    - index: index.md
    - about: about.md
    - 环境搭建: [
                  env_build/my_wiki.md,
                  env_build/tomcat.md,
                  env_build/rabbitmq_server.md,
                  env_build/google_ssr.md,
        ]
    - python: 
        - environment: [
                  python/python_setup.md,
                  python/python_package.md,
                  python/useful_package.md,
                  python/PEP8_standard.md,
                  python/requirements.md,
                  python/jupyter.md,
                  python/multi_version.md,
                  python/pip.md,
        ]
        - basic: [ 
                  python/dict.md,
                  python/file.md,
                  python/dataframe.md,
                  python/type.md,
                  python/list.md,
                  python/shell.md,
                  python/network.md,
                  python/path.md,
                  python/regular_expression.md,
                  python/copy.md
        ]
        - useful_module: [
                  python/useful_module/excel操作.md,
                  python/useful_module/tkinter.md,
                  python/useful_module/auto_inform.md,
                  python/useful_module/crawler_example.md,
                  python/useful_module/sort_by_num.md,
                  python/useful_module/聊天机器人.md,
                  python/useful_module/数据可视化.md,
                  python/useful_module/买房还是租房.md,
                  python/useful_module/usb_device.md,
                  
        ]
        - tools: [
                  python/pyinstaller.md,
        ]
               
    - C/C++:  
        - basic: [ 
                  c/shift.md,
                  c/inline.md,
                  c/hash.md,
                  c/file.md,
                  c/memory.md,
                  c/strings.md,
                  c/vs2013_err_code.md,
        ]
        - useful_module: [
                  c/merge_sort.md,
        
        ]
               
    - linux:  [   
                  linux/sleep.md,
                  linux/top.md,
                  linux/VM文件共享.md,
                  linux/vim.md,
                  linux/压缩解压.md,
                  linux/搜狗输入法安装.md,
        ]
    
    - git: 
        - environment: [
                  git/local_git.md, 
                  git/aliyun_git.md
        ]
        - basic: [
                  git/common_cmd.md,
                  git/git_reset.md,
                  git/add.md,
                  git/clear.md,
                  git/branch.md,
                  git/branch_recovery.md
        ]
        
    - 优化技术: [
                  opt/优化技术综述.md,
                  opt/exp近似运算.md,
                  opt/log快速计算.md,
                  opt/profile工具.md,
                  opt/除法运算.md,
                  opt/复数求模近似运算.md,
                  opt/快速取余.md,
                  opt/提高cache命中率.md,
    
        ]
        
    - 常用工具: 
        - tools: [
                  tools/超高效率工具.md,
                  tools/icon.md,
                  tools/mkdocs.md,
                  tools/notepad2.md,
        ]

    - 随笔文章: []